export { default as Header } from './Header'
export { default as Hero } from './Hero'
export { default as News } from './News'
export { default as LiveScores } from './LiveScores'
export { default as ManagerQuotes } from './ManagerQuotes'
export { default as Stats } from './Stats'
export { default as VideoHighlights } from './VideoHighlights'
export { default as Gallery } from './Gallery'
export { default as About } from './About'
export { default as CTA } from './CTA'
export { default as Footer } from './Footer'

